update

diff --git a/mpctitle-7 b/mpctitle-7
--- a/mpctitle-7
+++ b/mpctitle-7
@@ -18,9 +18,9 @@ lingercmd=( '/usr/local/bin/mpdgolinger' )
 source /usr/local/bin/editscript
 source /etc/default/mpdignore
 : "${mpdignorelib:=/usr/local/lib/mpdignore.functions}"
-source "$mpdignorelib"
+#source "$mpdignorelib"
 # cklinger() sourced
-source <(sourcefn -l "$mpdignorelib" -f cklinger --text)
+source <(sourcefn -l "$mpdignorelib" -f title -f hr2 -f cklinger -f sex2sec)
 [[ -r "$HOME/.config/mpd-local.conf" ]] && config="$HOME/.config/mpd-local.conf"
 
 # [[ ! "$mpdhost" ]] && mpdhost=[—redacted—]
@@ -176,7 +176,8 @@ getlast(){
   [[ "$1" = mpd.log.? ]] && mpdlog="$1"
   mpdlog="${mpdlog:=mpd.log}"
 
-  if { [[ "$mpdhost" = "localhost" ]] || (( usempdtags )); } && command -v mpdtags >/dev/null; then
+  if { [[ "$mpdhost" = "localhost" ]] || (( usempdtags )); } && command -v mpdtags >/dev/null && [[ "$1" != --logstream ]]; then
+    (( verbose )) && printf 'usempdtags=%s; mpdhost=%s; command -v mpdtags="%s"\n' "$usempdtags" "$mpdhost" "$(command -v mpdtags)"
     local completed
     local file
     local artist
@@ -205,18 +206,19 @@ getlast(){
     mpdlog="$logdir/${mpdlog:-mpd.log}"
     if (( usempdtags )); then source <(ssh gigabyte mpdtags --last="$mpdlog")
     else source <(mpdtags --last="$mpdlog"); fi
+    [[ ! "$file" ]] && getlast --logstream
     lastfullpath="$musicdir/$file"
     lastpath="$file"
     lastartist="$artist"
     lasttitle="$title"
     lastfile="${file##*/}"
     lastalbum="$album"
-#    logstream="tac /var/log/mpd/$mpdlog 2>&1"
-##   to silence:
-##   "tac: failed to open '/var/log/mpd/mpd.log' for reading: No such file or directory"
-##   if log file is missing:
-##   logstream="tac /var/log/mpd/$mpdlog 2>/dev/null"
-##   or handle with logstream="tac /var/log/mpd/$mpdlog &>"
+#   logstream="tac /var/log/mpd/$mpdlog 2>&1"
+##  to silence:
+##  "tac: failed to open '/var/log/mpd/mpd.log' for reading: No such file or directory"
+##  if log file is missing:
+##  logstream="tac /var/log/mpd/$mpdlog 2>/dev/null"
+##  or handle with logstream="tac /var/log/mpd/$mpdlog &>"
     (( verbose )) && { printf 'lastfullpath=%s\n' "$lastfullpath"
                        printf '    lastpath=%s\n' "$lastpath"
                        printf '    lastfile=%s\n' "$lastfile"
@@ -225,62 +227,64 @@ getlast(){
                        printf '   lastalbum=%s\n' "$lastalbum"
 #                       read -rp "Continue... " </dev/tty
                       }
+  (( verbose )) && read -rp "Continue..."
   else
     [[ "$mpdhost" = localhost ]] && logstream="tac /var/log/mpd/$mpdlog 2>&1" ||
       logstream="ssh -p \"$sshport\" \"$mpchost\" \"tac '/var/log/mpd/$mpdlog'\""
 
-  while read -r logline; do
-    if [[ "$logline" = "tac: failed to open '/var/log/mpd/mpd.log"*"for reading: No such file or directory" ]]; then
-      printf 'MPD logfile /var/log/mpd/%s missing.\n' "$mpdlog"
-      break
-    elif [[ "$logline" =~ .+\ player:\ (played|skipped)\ \"(((.+\/)?.+\ --\ (.+))\/([0-9]{1,3}?-?[0-9]{1,3}\ -\ (.+)\ --\ (.+)\..+))\" ]]; then
-      lastfullpath="$musicdir/${BASH_REMATCH[2]}"
-      lastpath="${BASH_REMATCH[2]}"
-      lastartist="${BASH_REMATCH[-2]}"
-      lasttitle="${BASH_REMATCH[-1]}"
-      lastfile="${BASH_REMATCH[-3]}"
-      lastalbum="${BASH_REMATCH[-4]%\(*}"
-      break
-    elif [[ "$logline" =~ .+\ player:\ (played|skipped)\ \"(((.+\/)?.+\ --\ (.+))\/((.+)\ --\ [0-9]{1,3}?-?[0-9]{1,3}\ -\ (.+)\..+))\" ]]; then
-      lastfullpath="$musicdir/${BASH_REMATCH[2]}"
-      lastpath="${BASH_REMATCH[2]}"
-      lastartist="${BASH_REMATCH[-2]}"
-      lasttitle="${BASH_REMATCH[-1]}"
-      lastfile="${BASH_REMATCH[-3]}"
-      lastalbum="${BASH_REMATCH[-4]%\(*}"
-      break
-    elif [[ "$logline" =~ .+\ player\:\ (played|skipped)\ \"((.+\/)?.+\ --\ (.+)\/(.+\..+))\" ]]; then
-      lastfullpath="$musicdir/${BASH_REMATCH[2]}"
-      lastpath="${BASH_REMATCH[2]}"
-      lastfile="${BASH_REMATCH[-1]}"
-      lastartist="THE FILE $lastfile DOES NOT FIT THE REGEX"
-      lasttitle="${BASH_REMATCH[-1]%.*}"
-      lastalbum="${BASH_REMATCH[-2]}"
-      break
-    elif [[ "$logline" =~ .+\ player\:\ (played|skipped)\ \"((.+)\/(.+\..+))\" ]]; then
-      lastfullpath="$musicdir/${BASH_REMATCH[2]}"
-      lastpath="${BASH_REMATCH[2]}"
-      lastfile="${BASH_REMATCH[-1]}"
-      lastartist="THE FILE $lastfile DOES NOT FIT THE REGEX"
-      lasttitle="${BASH_REMATCH[-1]%.*}"
-      lastalbum="${BASH_REMATCH[2]}"
-      break
-    elif [[ "$logline" = tac\:\ * ]]; then
-      [[ "$logline" != "$tacwarn" ]] &&
-        { printf 'Investigate unknown error with tac:\n%s\n' "$logline";
-          tacwarn="$logline"; }
-    fi
-    (( verbose )) && { printf 'lastfullpath=%s\n' "$lastfullpath"
-                       printf '    lastpath=%s\n' "$lastpath"
-                       printf '    lastfile=%s\n' "$lastfile"
-                       printf '  lastartist=%s\n' "$lastartist"
-                       printf '   lasttitle=%s\n' "$lasttitle"
-                       printf '   lastalbum=%s\n' "$lastalbum"
-#                       read -rp "Continue... " </dev/tty
-                      }
+    while read -r logline; do
+      (( verbose )) && printf 'In `while read -r logline` loop\n'
+      if [[ "$logline" = "tac: failed to open '/var/log/mpd/mpd.log"*"for reading: No such file or directory" ]]; then
+        printf 'MPD logfile /var/log/mpd/%s missing.\n' "$mpdlog"
+        break
+      elif [[ "$logline" =~ .+\ player:\ (played|skipped)\ \"(((.+\/)?.+\ --\ (.+))\/([0-9]{1,3}?-?[0-9]{1,3}\ -\ (.+)\ --\ (.+)\..+))\" ]]; then
+        lastfullpath="$musicdir/${BASH_REMATCH[2]}"
+        lastpath="${BASH_REMATCH[2]}"
+        lastartist="${BASH_REMATCH[-2]}"
+        lasttitle="${BASH_REMATCH[-1]}"
+        lastfile="${BASH_REMATCH[-3]}"
+        lastalbum="${BASH_REMATCH[-4]%\(*}"
+        break
+      elif [[ "$logline" =~ .+\ player:\ (played|skipped)\ \"(((.+\/)?.+\ --\ (.+))\/((.+)\ --\ [0-9]{1,3}?-?[0-9]{1,3}\ -\ (.+)\..+))\" ]]; then
+        lastfullpath="$musicdir/${BASH_REMATCH[2]}"
+        lastpath="${BASH_REMATCH[2]}"
+        lastartist="${BASH_REMATCH[-2]}"
+        lasttitle="${BASH_REMATCH[-1]}"
+        lastfile="${BASH_REMATCH[-3]}"
+        lastalbum="${BASH_REMATCH[-4]%\(*}"
+        break
+      elif [[ "$logline" =~ .+\ player\:\ (played|skipped)\ \"((.+\/)?.+\ --\ (.+)\/(.+\..+))\" ]]; then
+        lastfullpath="$musicdir/${BASH_REMATCH[2]}"
+        lastpath="${BASH_REMATCH[2]}"
+        lastfile="${BASH_REMATCH[-1]}"
+        lastartist="THE FILE $lastfile DOES NOT FIT THE REGEX"
+        lasttitle="${BASH_REMATCH[-1]%.*}"
+        lastalbum="${BASH_REMATCH[-2]}"
+        break
+      elif [[ "$logline" =~ .+\ player\:\ (played|skipped)\ \"((.+)\/(.+\..+))\" ]]; then
+        lastfullpath="$musicdir/${BASH_REMATCH[2]}"
+        lastpath="${BASH_REMATCH[2]}"
+        lastfile="${BASH_REMATCH[-1]}"
+        lastartist="THE FILE $lastfile DOES NOT FIT THE REGEX"
+        lasttitle="${BASH_REMATCH[-1]%.*}"
+        lastalbum="${BASH_REMATCH[2]}"
+        break
+      elif [[ "$logline" = tac\:\ * ]]; then
+        [[ "$logline" != "$tacwarn" ]] &&
+          { printf 'Investigate unknown error with tac:\n%s\n' "$logline";
+            tacwarn="$logline"; }
+      fi
+      (( verbose )) && { printf 'lastfullpath=%s\n' "$lastfullpath"
+                         printf '    lastpath=%s\n' "$lastpath"
+                         printf '    lastfile=%s\n' "$lastfile"
+                         printf '  lastartist=%s\n' "$lastartist"
+                         printf '   lasttitle=%s\n' "$lasttitle"
+                         printf '   lastalbum=%s\n' "$lastalbum"
+  #                       read -rp "Continue... " </dev/tty
+                        }
 
-  done < <(eval "$logstream" 2>/tmp/lastpath.err)
-fi
+    done < <(eval "$logstream" 2>/tmp/lastpath.err)
+  fi
 
   # SSH error handling
   if [[ -f /tmp/lastpath.err ]]; then
@@ -297,6 +301,7 @@ fi
     [[ "${lastpatherr[0]}" ]] && printf "..\n\n%s\n" "${lastpatherr[0]}"
   fi
 
+  (( verbose )) && printf '[verbose] lastfile=%s\n' "$lastfile"
   # Final fallbacks (in case no match was found)
   if [[ -z "$lastfile" ]]; then
     if [[ "$mpdlog" = mpd.log.* ]]; then
@@ -656,12 +661,14 @@ done
 #source <(mpd-current.py)
 #source <(mpd-current -p)
 
-[[ -r "$config" ]] && . "$config" || { printf 'Error sourcing --config file, %s. (exit 1)\n'; exit 1; }
+[[ -r "$config" ]] && source "$config" || { printf 'Error sourcing --config file, %s. (exit 1)\n'; exit 1; }
 
 if ! (( fromnext )); then
   getlast
   output=( "$(echo "$c_aa_que"; hr2 LAST)" )
   output+=( "$(title last)" ) || { echo "Check $mpdlog"; exit 1; }
+else
+  cklinger
 fi
 
 mpdcurrent
@@ -723,7 +730,7 @@ output+=( "$(printf '          volume: %s%%%s %s %s random: %s%s%s consume: %s%s
   "${single:+single: $single}" \
   "$tput0" )" )
 
-(( ! lingeron )) && cklinger
+(( ! lingeron && ! fromnext )) && cklinger
 (( verbose )) && printf '[verbose] $lingerxy=%s\n' "$lingerxy"
 (( lingeron )) && {
                     (( lingerlimit != lingerbase )) &&
